### ISSUE TITLE
nullclient bug

### ISSUE THREAD

**Issue by decibelhertz** [smoeding/puppet-sendmail#11]
https://github.com/smoeding/puppet-sendmail/blob/master/manifests/nullclient.pp#L99 shows that the default value is `undef`, but https://github.com/smoeding/puppet-sendmail/blob/master/manifests/nullclient.pp#L129 shows that the `validate_re()` function will make that default value fail, since undef is not a string, nor would an empty string match the regex provided.

Two solutions come to mind; I'm not quite sure which you'd prefer, so will spell them out:
1. Wrap the `validate_re()` call in a conditional, e.g.
```puppet
if undef != $port_option_modify { validate_re($port_option_modify, '^[abcfhruACEOS]*$') }
```
2. Remove the default value from line 99 and force the user specify `$port_option_modify` much like you do for `$mail_hub`.

**Comment by smoeding** [comment]
Thanks for catching this issue. It is caused by a more strict behaviour of stdlib 4.14 or later. I will use your first solution as a fix.

**Comment by decibelhertz** [comment]
Glad to help.  Cheers.
