### ISSUE TITLE
authinfo entries location

### ISSUE THREAD

**Issue by kwilcox77** [smoeding/puppet-sendmail#13]
Any authinfo entries created in /etc/mail/authinfo seem to be ignored (for me at least) on Redhat/CentOS.  The sendmail documentation recommends that you put authinfo entries into the /etc/mail/access file, however I don't think I am able to do this using your module.  If I manually put my authinfo entries into the access file and recompile it does seem to work ok.

Am I doing something wrong with your authinfo parameter? Or does this functionality not exist?

Many Thanks

Kev

**Comment by smoeding** [comment]
How do the authinfo related parts of your Puppet manifest look?

The `sendmail::authinfo::entry` type creates an entry in the `/etc/mail/authinfo` file. Does the entry appear? It also should trigger a rebuild of the database file. Does the file `/etc/mail/authinfo.db` exist and has it a current timestamp?

You also need to enable the authinfo processing for Sendmail by adding an appropriate feature. Do you have a line like `sendmail::mc::feature { 'authinfo': }` in your Puppet manifest?

**Comment by kwilcox77** [comment]
Thanks for the reply!

The /etc/mail/authino file has the correct information and the authinfo.db exists and has the correct timestamps.  I didn't have a sendmail::mc::feature { 'authinfo': } section but I was testing by turning off puppet on my affected host and adding the following line to speed up testing:

FEATURE(`authinfo', `hash /etc/mail/authinfo.db')dnl

I was then doing a "make -C /etc/mail" and restarting sendmail.  The credentials still seem to get ignored.  My apologies for my ignorance on this as this is slightly new territory for me.  When we used to set up the hosts manually, we used to just put an authinfo entry in /etc/mail/access with no further configuration and it just worked.

Cheers

Kev

**Comment by smoeding** [comment]
According to [sendmail.org](http://www.sendmail.org/~ca/email/auth.html#smtpclient) there is one difference between entries in access.db and authinfo.db:

> Note: if FEATURE(`authinfo') is used, then the hostname in the map entry must match exactly the hostname of the ISP mailserver as explained in cf/README: Note: searches for domain parts or IP nets are only performed if the access map is used; if the authinfo feature is used then only up to three lookups are performed (two exact matches, one default).

Could this be your issue?

**Comment by kwilcox77** [comment]
Ah - I think you may be right, unless I'm getting confused, I have a mailertable file which directs to different relays based on domain.
If this is my issue - is there anything I can do?  
Would I need to insert the Authinfo text in the access file myself?

Cheers

Kev

**Comment by smoeding** [comment]
Let me see, if I understand you correctly: currently you have something like 
```
AuthInfo:.example.com "U:USERNAME" "P:PASSWORD" "M:PLAIN"
```

in your `access.db`. If you put that entry into `authinfo.db` it will not work, because it doesn't specify the complete destination host as key. You use the mailertable to route your mail to either `host1.example.com` or `host2.example.com` or `host3.example.com` and so on. So you would have to add an individual authinfo entry for each of these hosts to make it work. That's how I understand it.

On the other hand it should be possible to use the `sendmail::access::entry` type to add the old entry to the `access.db`:

```
sendmail::access::entry { 'AuthInfo:.example.com':
  value => '"U:USERNAME" "P:PASSWORD" "M:PLAIN"',
}
```

This should give you the same setup you currently use.

**Comment by kwilcox77** [comment]
OK great thanks - I won't have the opportunity to test this until early next week so I'll try both options and let you know if this works - thanks very much for your help!

**Comment by kwilcox77** [comment]
I just thought I'd let you know that, although I didn't have time to try both options, modifying the sendmail access entry worked!

Thanks so much for your help!

Kev
