### ISSUE TITLE
Augeas can't find lens

### ISSUE THREAD

**Issue by jarro2783** [smoeding/puppet-sendmail#14]
I get this error when I run puppet:
```
Debug: Augeas[/etc/mail/virtusertable-phabricator](provider=augeas): /augeas/load/Xfm/error = Can not find lens Sendmail_Map.lns
```

Is there some trick to make this use the bundled lens?

**Comment by smoeding** [comment]
No, there shouldn't be any trick necessary.

How does your environment look? What version of Puppet are you using? Do you run a Puppetmaster or do you use `puppet apply` (that might be a reason)? Do you have pluginsync enabled (it is by default) in your config file?

**Comment by jarro2783** [comment]
I'm just using `puppet apply`. I don't have an explicit setting for `pluginsync`. I'm on Puppet 4.10.1.

**Comment by smoeding** [comment]
Ah, so it is probably caused by this (unresolved) issue: https://tickets.puppetlabs.com/browse/PUP-1206
Maybe the workaround will also work for you?

**Comment by jarro2783** [comment]
Oh I see. Thanks. I didn't find that issue when I was looking.

**Comment by smoeding** [comment]
Closing as it is not an issue with this module.
