### ISSUE TITLE
outdated dependency

### ISSUE THREAD

**Issue by vbinet** [smoeding/puppet-sendmail#17]
The current version of puppetlabs.concat is 4.2.1 but your stm-sendmail module still requires a version (>= 1.2.0 < 3.0.0) for concat.
This creates unresolved dependencies when using stm-sendmail with other modules requiring a newer version of concat.
Please test with a new version of concat and update your dependencies. Thank you.

**Comment by smoeding** [comment]
Fixed in version 1.3.2 of the module, which is now available on the Puppet Forge:
https://forge.puppet.com/stm/sendmail/dependencies

**Comment by vbinet** [comment]
I tried to get your new module with the new concat and got this:
# puppetserver ruby "$(which librarian-puppet)" install
NoMethodError: undefined method `source' for nil:NilClass
  extract_and_parse_dependencies at
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/librarianp-0.6.3/lib/librarian/lockfile/parser.rb:69
  extract_and_parse_dependencies at
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/librarian-puppet-2.2.0/lib/librarian/puppet/lockfile.rb:28
                           parse at
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/librarianp-0.6.3/lib/librarian/lockfile/parser.rb:29
                            load at
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/librarian-puppet-2.2.0/lib/librarian/puppet/lockfile.rb:34
                            read at
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/librarianp-0.6.3/lib/librarian/lockfile.rb:25
                             run at
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/librarianp-0.6.3/lib/librarian/action/resolve.rb:16
                             run at
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/librarian-puppet-2.2.0/lib/librarian/puppet/action/resolve.rb:10
                        resolve! at
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/librarian-puppet-2.2.0/lib/librarian/puppet/cli.rb:104
                         install at
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/librarian-puppet-2.2.0/lib/librarian/puppet/cli.rb:68
                             run at
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/thor-0.19.1/lib/thor/command.rb:27
                  invoke_command at
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/thor-0.19.1/lib/thor/invocation.rb:126
                        dispatch at
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/thor-0.19.1/lib/thor.rb:359
                           start at
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/thor-0.19.1/lib/thor/base.rb:440
                            bin! at
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/librarianp-0.6.3/lib/librarian/cli.rb:26
                returning_status at
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/librarianp-0.6.3/lib/librarian/cli.rb:31
                            bin! at
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/librarianp-0.6.3/lib/librarian/cli.rb:26
                with_environment at
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/librarianp-0.6.3/lib/librarian/cli.rb:47
                            bin! at
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/librarianp-0.6.3/lib/librarian/cli.rb:26
                          (root) at
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/librarian-puppet-2.2.0/bin/librarian-puppet:7
                            load at org/jruby/RubyKernel.java:1059
                          (root) at /opt/puppetlabs/bin/librarian-puppet:1
                          invoke at jruby_core.clj:259
                          invoke at jruby_core.clj:253
                    invokeStatic at ruby.clj:9
                          invoke at ruby.clj:6
                    invokeStatic at subcommand.clj:37
                          invoke at subcommand.clj:26
                    invokeStatic at ruby.clj:13
                        doInvoke at ruby.clj:11
                    invokeStatic at core.clj:646
                    invokeStatic at main.clj:314
                          invoke at main.clj:310
                    invokeStatic at main.clj:421
                        doInvoke at main.clj:384

No idea whether the problem is on your side or with the concat module
though.
I don't have that issue with sendmail 1.3.0 and concat 2.2.1.

Valère Binet

**Comment by smoeding** [comment]
The error seems to be with librarian-puppet which I don't know. I'm using r10k to deploy the code and I don't see any errors using that tool. I tried removing both the sendmail and the concat module and r10k deploys both modules in their latest version without any problem.
