### ISSUE TITLE
On CentOS 7.4.1708 I get makemap not found

### ISSUE THREAD

**Issue by prismhr-smartin** [smoeding/puppet-sendmail#18]
With CentOS 7 I was getting the following issue.

[root@947057-2rpmr001 ~]# /opt/puppetlabs/bin/puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for 947057-2rpmr001.davison.local
Info: Applying configuration version '1527003903'
Error: Systemd start for sendmail failed!
journalctl log for sendmail:
-- Logs begin at Sat 2018-05-12 22:26:06 CDT, end at Tue 2018-05-22 10:46:36 CDT. --
May 22 10:44:37 947057-2rpmr001.davison.local systemd[1]: Starting Sendmail Mail Transport Agent...
May 22 10:44:37 947057-2rpmr001.davison.local make[26990]: /etc/mail/make: line 22: makemap: command not found
May 22 10:44:37 947057-2rpmr001.davison.local make[26990]: /etc/mail/make: line 22: makemap: command not found
May 22 10:44:37 947057-2rpmr001.davison.local make[26990]: /etc/mail/make: line 22: makemap: command not found
May 22 10:44:37 947057-2rpmr001.davison.local make[26990]: /etc/mail/make: line 22: makemap: command not found
May 22 10:44:37 947057-2rpmr001.davison.local systemd[1]: PID file /run/sendmail.pid not readable (yet?) after start.
May 22 10:44:38 947057-2rpmr001.davison.local postfix/postfix-script[27018]: fatal: the Postfix mail system is already running
May 22 10:44:38 947057-2rpmr001.davison.local systemd[1]: sendmail.service never wrote its PID file. Failing.
May 22 10:44:38 947057-2rpmr001.davison.local systemd[1]: Failed to start Sendmail Mail Transport Agent.
May 22 10:44:38 947057-2rpmr001.davison.local systemd[1]: Unit sendmail.service entered failed state.
May 22 10:44:38 947057-2rpmr001.davison.local systemd[1]: sendmail.service failed.
May 22 10:45:06 947057-2rpmr001.davison.local systemd[1]: Starting Sendmail Mail Transport Agent...
May 22 10:45:06 947057-2rpmr001.davison.local make[27182]: /etc/mail/make: line 22: makemap: command not found
May 22 10:45:06 947057-2rpmr001.davison.local make[27182]: /etc/mail/make: line 22: makemap: command not found
May 22 10:45:06 947057-2rpmr001.davison.local make[27182]: /etc/mail/make: line 22: makemap: command not found
May 22 10:45:06 947057-2rpmr001.davison.local make[27182]: /etc/mail/make: line 22: makemap: command not found
May 22 10:45:06 947057-2rpmr001.davison.local systemd[1]: PID file /run/sendmail.pid not readable (yet?) after start.
May 22 10:45:07 947057-2rpmr001.davison.local postfix/master[27269]: daemon started -- version 2.10.1, configuration /etc/postfix
May 22 10:46:36 947057-2rpmr001.davison.local systemd[1]: sendmail.service start operation timed out. Terminating.
May 22 10:46:36 947057-2rpmr001.davison.local systemd[1]: Failed to start Sendmail Mail Transport Agent.
May 22 10:46:36 947057-2rpmr001.davison.local systemd[1]: Unit sendmail.service entered failed state.
May 22 10:46:36 947057-2rpmr001.davison.local systemd[1]: sendmail.service failed.

Error: /Stage[main]/Sendmail::Service/Service[sendmail]/ensure: change from stopped to running failed: Systemd start for sendmail failed!
journalctl log for sendmail:
-- Logs begin at Sat 2018-05-12 22:26:06 CDT, end at Tue 2018-05-22 10:46:36 CDT. --
May 22 10:44:37 947057-2rpmr001.davison.local systemd[1]: Starting Sendmail Mail Transport Agent...
May 22 10:44:37 947057-2rpmr001.davison.local make[26990]: /etc/mail/make: line 22: makemap: command not found
May 22 10:44:37 947057-2rpmr001.davison.local make[26990]: /etc/mail/make: line 22: makemap: command not found
May 22 10:44:37 947057-2rpmr001.davison.local make[26990]: /etc/mail/make: line 22: makemap: command not found
May 22 10:44:37 947057-2rpmr001.davison.local make[26990]: /etc/mail/make: line 22: makemap: command not found
May 22 10:44:37 947057-2rpmr001.davison.local systemd[1]: PID file /run/sendmail.pid not readable (yet?) after start.
May 22 10:44:38 947057-2rpmr001.davison.local postfix/postfix-script[27018]: fatal: the Postfix mail system is already running
May 22 10:44:38 947057-2rpmr001.davison.local systemd[1]: sendmail.service never wrote its PID file. Failing.
May 22 10:44:38 947057-2rpmr001.davison.local systemd[1]: Failed to start Sendmail Mail Transport Agent.
May 22 10:44:38 947057-2rpmr001.davison.local systemd[1]: Unit sendmail.service entered failed state.
May 22 10:44:38 947057-2rpmr001.davison.local systemd[1]: sendmail.service failed.
May 22 10:45:06 947057-2rpmr001.davison.local systemd[1]: Starting Sendmail Mail Transport Agent...
May 22 10:45:06 947057-2rpmr001.davison.local make[27182]: /etc/mail/make: line 22: makemap: command not found
May 22 10:45:06 947057-2rpmr001.davison.local make[27182]: /etc/mail/make: line 22: makemap: command not found
May 22 10:45:06 947057-2rpmr001.davison.local make[27182]: /etc/mail/make: line 22: makemap: command not found
May 22 10:45:06 947057-2rpmr001.davison.local make[27182]: /etc/mail/make: line 22: makemap: command not found
May 22 10:45:06 947057-2rpmr001.davison.local systemd[1]: PID file /run/sendmail.pid not readable (yet?) after start.
May 22 10:45:07 947057-2rpmr001.davison.local postfix/master[27269]: daemon started -- version 2.10.1, configuration /etc/postfix
May 22 10:46:36 947057-2rpmr001.davison.local systemd[1]: sendmail.service start operation timed out. Terminating.
May 22 10:46:36 947057-2rpmr001.davison.local systemd[1]: Failed to start Sendmail Mail Transport Agent.
May 22 10:46:36 947057-2rpmr001.davison.local systemd[1]: Unit sendmail.service entered failed state.
May 22 10:46:36 947057-2rpmr001.davison.local systemd[1]: sendmail.service failed.

Notice: /Stage[main]/Sendmail/Anchor[sendmail::end]: Dependency Service[sendmail] has failures: true
Warning: /Stage[main]/Sendmail/Anchor[sendmail::end]: Skipping because of failed dependencies
Notice: Applied catalog in 91.27 seconds

I looked into it a little bit and the link for makemap was bad.

[root@947057-2rpmr001 ~]# ls -lah /usr/bin/makemap
lrwxrwxrwx. 1 root root 15 May 22 10:44 /usr/bin/makemap -> ../sbin/makemap

But the executable is "/usr/sbin/makemap.sendmail"

So I fixed the link
cd /usr/bin
rm makemap
ln -s ../sbin/makemap.sendmail makemap

**Comment by smoeding** [comment]
This seems to be a problem with the CentOS sendmail package or your installation.

I'm not calling {{makemap}} directly in the code. Instead I call {{make -C /etc/mail}} to update the databases. On CentOS this seems to use {{/etc/mail/make}} which tries to call the (missing) {{makemap}} executable in line 22 (see your error message above).

You also have messages in your log that you run Postfix at the same time. This might also interfere with the Sendmail installation.

**Comment by smoeding** [comment]
I only have CentOS 7.5 available:
```
[root@centos7 mail]# cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
```
Your missing executable is part of the sendmail package there:

```
[root@centos7 mail]# rpm -qf /sbin/makemap.sendmail
sendmail-8.14.7-5.el7.x86_64
```

I'm closing this now, because it looks like a configuration issue on your side and not a problem with the Puppet module.
