### ISSUE TITLE
Generics Domain feature is not present in the module

### ISSUE THREAD

**Issue by saimailbox86** [smoeding/puppet-sendmail#19]
Hi,

Could you please add the Generics Domain Feature to the module. 
Example: GENERICS_DOMAIN(`xxxxx.mycompany.net')dnl

The module currently only supports sendmail::mc::domain { 'xxxx.mycompany.net': } which results in the output of sendmail.mc as 

DOMAIN('xxxx.mycompany.net')dnl

**Comment by trlinkin** [comment]
Additional documentation: http://etutorials.org/Server+Administration/Sendmail/Part+I+Build+and+Install/Chapter+4.+Configure+sendmail.cf+with+m4/FEATUREgenericstable/

**Comment by smoeding** [comment]
I just released version 1.4.1 of the module on the Puppet Forge. This version adds the requested generics domain macro. Now you can use

```
sendmail::mc::generics_domain { 'xxxx.mycompany.net': }
```

to add the `GENERICS_DOMAIN()` macro to the `sendmail.mc` file.
